name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  r-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Set up pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/R/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: ${{ runner.os }}-renv-

      - name: Install renv
        run: R -q -e 'install.packages("renv", repos="https://cloud.r-project.org")'

      - name: Restore packages
        run: |
          R -q -e 'if (file.exists("renv.lock")) renv::restore() else renv::init(); renv::install(c("lintr","readr","janitor","yaml","ggplot2"))'

      - name: Lint
        run: R -q -e 'lintr::lint_dir("R")'

      - name: Smoke check
        run: R -q -e 'source("R/00_smoke_check.R")'

      - name: Aggregate results
        run: R -q -e 'source("R/10_aggregate_results.R")'

      - name: Make figures
        run: R -q -e 'source("R/20_make_figures.R")'